import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {TheHeader} from "@/app/components/TheHeader";
import {TheFooter} from "@/app/components/TheFooter";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <TheHeader/>
      <main className={'flex items-center justify-center flex-col'}>{children}</main>
      <TheFooter/>
      </body>
    </html>
  )
}
